program Gerencial;

uses
  Forms,
  Windows,
  Dialogs,
  System.SysUtils,
  principal in 'fnts\principal.pas' {frmPrincipal},
  modulo in 'fnts\modulo.pas' {frmmodulo: TDataModule},
  setor in 'fnts\setor.pas' {frmSetor},
  loc_setor in 'fnts\loc_setor.pas' {frmloc_setor},
  loc_grupo_servico in 'fnts\loc_grupo_servico.pas' {frmloc_grupo_servico},
  convenio in 'fnts\convenio.pas' {frmconvenio},
  funcionario in 'fnts\funcionario.pas' {frmfuncionario},
  contacorrente in 'fnts\contacorrente.pas' {frmcontacorrente},
  banco in 'fnts\banco.pas' {frmbanco},
  cheque_avulso in 'fnts\cheque_avulso.pas' {frmcheque_avulso},
  condpgto in 'fnts\condpgto.pas' {frmcondpgto},
  loc_regiao in 'fnts\loc_regiao.pas' {frmloc_regiao},
  loc_conta in 'fnts\loc_conta.pas' {frmloc_conta},
  webcam in 'fnts\webcam.pas' {frmwebcam},
  plano in 'fnts\plano.pas' {frmplano},
  fornecedor in 'fnts\fornecedor.pas' {frmfornecedor},
  produto_preco in 'fnts\produto_preco.pas' {frmproduto_preco},
  caixa_operador in 'fnts\caixa_operador.pas' {frmCaixa_operador},
  produto_pedido in 'fnts\produto_pedido.pas' {frmproduto_pedido},
  produto_pedido_item in 'fnts\produto_pedido_item.pas' {frmproduto_pedido_item},
  produto_grade_pedido in 'fnts\produto_grade_pedido.pas' {frmproduto_grade_pedido},
  loc_fornecedor in 'fnts\loc_fornecedor.pas' {frmLoc_fornecedor},
  Cheque_baixa in 'fnts\Cheque_baixa.pas' {frmcheque_baixa},
  cliente_veiculo in 'fnts\cliente_veiculo.pas' {frmcliente_veiculo},
  contacorrente_lancamento2 in 'fnts\contacorrente_lancamento2.pas' {frmcontacorrente_lancamento2},
  contacorrente_ficha in 'fnts\contacorrente_ficha.pas' {frmcontacorrente_ficha},
  loc_contacorrent in 'fnts\loc_contacorrent.pas' {frmloc_contacorrente},
  loc_banco in 'fnts\loc_banco.pas' {frmloc_banco},
  contacorrente_lancamento in 'fnts\contacorrente_lancamento.pas' {frmcontacorrente_lancamento},
  servico in 'fnts\servico.pas' {frmservico},
  caixa_abertura_individual in 'fnts\caixa_abertura_individual.pas' {frmcaixa_abertura_individual},
  caixa_abertura in 'fnts\caixa_abertura.pas' {frmcaixa_abertura},
  caixa_fechamento in 'fnts\caixa_fechamento.pas' {frmcaixa_fechamento},
  caixa_ficha in 'fnts\caixa_ficha.pas' {frmcaixa_ficha},
  contaspagar in 'fnts\contaspagar.pas' {frmcontaspagar},
  contaspagar_fichaalteracao in 'fnts\contaspagar_fichaalteracao.pas' {frmcontaspagar_fichaAlteracao},
  contaspagar_pgto in 'fnts\contaspagar_pgto.pas' {frmcontaspagar_pgto},
  contaspagar_cheque in 'fnts\contaspagar_cheque.pas' {frmcontaspagar_cheque},
  venda in 'fnts\venda.pas' {frmvenda},
  venda_inicio in 'fnts\venda_inicio.pas' {frmvenda_inicio},
  os_serial in 'fnts\os_serial.pas' {frmos_serial},
  venda_grade in 'fnts\venda_grade.pas' {frmvenda_grade},
  os_fechamento_auto in 'fnts\os_fechamento_auto.pas' {frmos_fechamento_auto},
  os_contasreceber_auto in 'fnts\os_contasreceber_auto.pas' {frmos_contasreceber_auto},
  troco in 'fnts\troco.pas' {frmvenda_troco},
  notas_venda_impressao in 'fnts\notas_venda_impressao.pas' {frmnotas_venda_impressao},
  venda_troca in 'fnts\venda_troca.pas' {frmvenda_troca},
  contasreceber in 'fnts\contasreceber.pas' {frmcontasreceber},
  contasreceber_banco in 'fnts\contasreceber_banco.pas' {frmContasreceber_banco},
  contasreceber_alterar in 'fnts\contasreceber_alterar.pas' {frmcontasreceber_alterar},
  contasreceber_ficha in 'fnts\contasreceber_ficha.pas' {frmcontasreceber_ficha},
  contasreceber_juros in 'fnts\contasreceber_juros.pas' {frmcontasreceber_juros},
  notas_venda in 'fnts\notas_venda.pas' {frmnotas_venda},
  os_impressao in 'fnts\os_impressao.pas' {frmos_impressao},
  os_auto in 'fnts\os_auto.pas' {frmOS_Auto},
  loc_veiculo in 'fnts\loc_veiculo.pas' {frmloc_veiculo},
  os_menu in 'fnts\os_menu.pas' {frmOs_menu},
  venda_serial in 'fnts\venda_serial.pas' {frmvenda_serial},
  cfop in 'fnts\cfop.pas' {frmcfop},
  orcamento_localizar in 'fnts\orcamento_localizar.pas' {frmOrcamento_localizar},
  loc_caixa in 'fnts\loc_caixa.pas' {frmloc_caixa},
  cliente_financeiro in 'fnts\cliente_financeiro.pas' {frmcliente_financeiro},
  veiculo in 'fnts\veiculo.pas' {frmveiculo},
  os in 'fnts\os.pas' {frmos},
  os_fechamento in 'fnts\os_fechamento.pas' {frmos_fechamento},
  os_contasreceber in 'fnts\os_contasreceber.pas' {frmos_contasreceber},
  Sintegra in 'fnts\Sintegra.pas',
  produto_total in 'fnts\produto_total.pas' {frmproduto_total},
  contasreceber_ficha_varios in 'fnts\contasreceber_ficha_varios.pas' {frmcontasreceber_ficha_varios},
  loc_grupo in 'fnts\loc_grupo.pas' {frmloc_grupo},
  loc_subgrupo in 'fnts\loc_subgrupo.pas' {frmloc_subgrupo},
  loc_marca in 'fnts\loc_marca.pas' {frmloc_marca},
  lista_transportador2 in 'fnts\lista_transportador2.pas' {frmlista_transportador2},
  xloc_funcionario in 'fnts\xloc_funcionario.pas' {frmxloc_Funcionario},
  lista_venda2 in 'fnts\lista_venda2.pas' {frmlista_venda2},
  lista_produto2 in 'fnts\lista_produto2.pas' {frmlista_produto2},
  extenso1 in 'fnts\extenso1.pas',
  xloc_cliente in 'fnts\xloc_cliente.pas' {frmxloc_cliente},
  lista_cliente2 in 'fnts\lista_cliente2.pas' {frmlista_cliente2},
  xloc_produto_entrada in 'fnts\xloc_produto_entrada.pas' {frmxloc_produto_entrada},
  xloc_banco in 'fnts\xloc_banco.pas' {frmxloc_banco},
  xloc_transportador in 'fnts\xloc_transportador.pas' {frmxloc_transportador},
  xloc_subgrupo in 'fnts\xloc_subgrupo.pas' {frmxloc_subgrupo},
  xloc_pessoas in 'fnts\xloc_pessoas.pas' {frmxloc_Pessoas},
  xloc_fornecedor in 'fnts\xloc_fornecedor.pas' {frmxloc_fornecedor},
  xloc_servico in 'fnts\xloc_servico.pas' {frmxloc_servico},
  xloc_empresa in 'fnts\xloc_empresa.pas' {frmxloc_empresa},
  xloc_gruposervico in 'fnts\xloc_gruposervico.pas' {frmxloc_gruposervico},
  lista_servicos_periodicos in 'fnts\lista_servicos_periodicos.pas' {frmlista_servicos_periodicos},
  lista_servicos2 in 'fnts\lista_servicos2.pas' {frmlista_servicos2},
  lista_planocontas2 in 'fnts\lista_planocontas2.pas' {frmlista_planocontas2},
  xloc_grupo in 'fnts\xloc_grupo.pas' {frmxloc_grupo},
  lista_funcionario2 in 'fnts\lista_funcionario2.pas' {frmlista_funcionario2},
  venda_obs in 'fnts\venda_obs.pas' {frmvenda_obs},
  lista_caixa2 in 'fnts\lista_caixa2.pas' {frmlista_caixa2},
  lista_os in 'fnts\lista_os.pas' {frmlista_os},
  lista_cheque2 in 'fnts\lista_cheque2.pas' {frmlista_cheque2},
  lista_pagar2 in 'fnts\lista_pagar2.pas' {frmlista_pagar2},
  xloc_notafiscal in 'fnts\xloc_notafiscal.pas' {frmxloc_notafiscal},
  config in 'fnts\config.pas' {frmconfig},
  xloc_conta in 'fnts\xloc_conta.pas' {frmxloc_CONTA},
  marca in 'fnts\marca.pas' {frmmarca},
  loc_funci_venda in 'fnts\loc_funci_venda.pas' {frmloc_funci_venda},
  balanca in 'fnts\balanca.pas' {frmbalanca},
  produto_atualizapreco in 'fnts\produto_atualizapreco.pas' {frmproduto_atualizapreco},
  xloc_veiculo in 'fnts\xloc_veiculo.pas' {frmxloc_veiculo},
  produto_consultapreco in 'fnts\produto_consultapreco.pas' {frmproduto_consultapreco},
  cheque_conta in 'fnts\cheque_conta.pas' {frmcheque_conta},
  lista_receber2 in 'fnts\lista_receber2.pas' {frmlista_receber2},
  contaspagar_data in 'fnts\contaspagar_data.pas' {frmcontaspagar_data},
  convenio_receber in 'fnts\convenio_receber.pas' {frmconvenio_receber},
  contasreceber_pgto in 'fnts\contasreceber_pgto.pas' {frmcontasreceber_pgto},
  transportador in 'fnts\transportador.pas' {frmtransportador},
  xloc_cheque in 'fnts\xloc_cheque.pas' {frmxloc_cheque},
  xloc_convenio in 'fnts\xloc_convenio.pas' {frmxloc_convenio},
  sintegra_menu in 'fnts\sintegra_menu.pas' {frmsintegra_menu},
  xloc_modelo in 'fnts\xloc_modelo.pas' {frmxloc_modelo},
  venda_contasreceber in 'fnts\venda_contasreceber.pas' {frmvenda_contasreceber},
  venda_nf in 'fnts\venda_nf.pas' {frmvenda_nf},
  produto_serial in 'fnts\produto_serial.pas' {frmproduto_serial},
  produto_gradeF in 'fnts\produto_gradeF.pas' {frmproduto_gradeF},
  compra in 'fnts\compra.pas' {frmcompra},
  compra_item in 'fnts\compra_item.pas' {frmcompra_item},
  etiqueta_grade in 'fnts\etiqueta_grade.pas' {frmetiqueta_grade},
  lista_fornecedor2 in 'fnts\lista_fornecedor2.pas' {frmlista_fornecedor2},
  lista_entrada_sintegra in 'fnts\lista_entrada_sintegra.pas' {frmlista_entrada_sintegra},
  lista_notasaida in 'fnts\lista_notasaida.pas' {frmlista_notasaida},
  lista_notacompra in 'fnts\lista_notacompra.pas' {frmlista_notacompra},
  compra_menu in 'fnts\compra_menu.pas' {frmcompra_menu},
  caixa in 'fnts\caixa.pas' {frmcaixa},
  cliente in 'fnts\cliente.pas' {frmcliente},
  venda_fechamento_especial in 'fnts\venda_fechamento_especial.pas' {frmvenda_fechamento_especial},
  mensagem_inventario in 'fnts\mensagem_inventario.pas' {frmmensagem_inventario},
  grupo in 'fnts\grupo.pas' {frmgrupo},
  etiquetador in 'fnts\etiquetador.pas' {frmetiquetador},
  notafiscal_impressao in 'fnts\notafiscal_impressao.pas' {frmnotafiscal_impressao},
  dados_inventario in 'fnts\dados_inventario.pas' {frmdados_inventario},
  fornecedor_compras in 'fnts\fornecedor_compras.pas' {frmfornecedor_compras},
  lista_cliente_financeiro in 'fnts\lista_cliente_financeiro.pas' {frmlista_cliente_financeiro: venda_item_2},
  baixa_estoque in 'fnts\baixa_estoque.pas' {frmbaixa_estoque},
  orcamento in 'fnts\orcamento.pas' {frmOrcamento},
  orcamento_impressao in 'fnts\orcamento_impressao.pas' {frmorcamento_impressao},
  venda_devolucao in 'fnts\venda_devolucao.pas' {frmvenda_devolucao},
  xloc_marca in 'fnts\xloc_marca.pas' {frmxloc_marca},
  grupo_servico in 'fnts\grupo_servico.pas' {frmgrupo_servico},
  produto in 'fnts\produto.pas' {frmproduto},
  xloc_cliente_veiculo in 'fnts\xloc_cliente_veiculo.pas' {frmxloc_cliente_veiculo},
  xloc_cfop in 'fnts\xloc_cfop.pas' {frmxloc_cfop},
  cheque_menu in 'fnts\cheque_menu.pas' {frmcheque_menu},
  cheque in 'fnts\cheque.pas' {frmcheque},
  produto_movimentar in 'fnts\produto_movimentar.pas' {frmproduto_movimentar},
  tamanho in 'fnts\tamanho.pas' {frmtamanho},
  produto_foto in 'fnts\produto_foto.pas' {frmproduto_foto},
  notafiscal_cancelar in 'fnts\notafiscal_cancelar.pas' {frmnotafiscal_cancelar},
  contaspagar_nf in 'fnts\contaspagar_nf.pas' {frmcontaspagar_nf},
  contasreceber_renegociar in 'fnts\contasreceber_renegociar.pas' {frmcontasreceber_renegociar},
  inventario in 'fnts\inventario.pas' {frmInventario},
  inventario_ficha in 'fnts\inventario_ficha.pas' {frminventario_ficha},
  loc_funci in 'fnts\loc_funci.pas' {frmloc_funci},
  nf_obs in 'fnts\nf_obs.pas' {frmnf_obs},
  entrega_ficha in 'fnts\entrega_ficha.pas' {frmEntrega_ficha},
  entrega in 'fnts\entrega.pas' {frmentrega},
  venda_entrega in 'fnts\venda_entrega.pas' {frmVenda_Entrega},
  baixa_localizar in 'fnts\baixa_localizar.pas' {frmbaixa_localizar},
  NotaFiscal_Item_grade in 'fnts\NotaFiscal_Item_grade.pas' {frmNotaFiscal_Item_grade},
  NotaFiscal_Item_serial in 'fnts\NotaFiscal_Item_serial.pas' {frmNotaFiscal_Item_Serial},
  contaspagar_ficha in 'fnts\contaspagar_ficha.pas' {frmcontaspagar_ficha},
  venda_financeira in 'fnts\venda_financeira.pas' {frmvenda_financeira},
  financeira_ficha in 'fnts\financeira_ficha.pas' {frmfinanceira_ficha},
  financeira in 'fnts\financeira.pas' {frmFinanceira},
  financeira_pgto in 'fnts\financeira_pgto.pas' {frmFinanceira_Pgto},
  xloc_financeira in 'fnts\xloc_financeira.pas' {frmxloc_financeira},
  financeira_alterar in 'fnts\financeira_alterar.pas' {frmfinanceira_alterar},
  lista_financeira in 'fnts\lista_financeira.pas' {frmlista_financeira},
  regiao in 'fnts\regiao.pas' {frmregiao},
  cliente_inicio in 'fnts\cliente_inicio.pas' {frmcliente_inicio},
  cartao in 'fnts\cartao.pas' {frmCartao},
  cartao_alterar in 'fnts\cartao_alterar.pas' {frmcartao_alterar},
  cartao_ficha in 'fnts\cartao_ficha.pas' {frmcartao_ficha},
  cartao_pgto in 'fnts\cartao_pgto.pas' {frmCartao_PGTO},
  lista_cartao in 'fnts\lista_cartao.pas' {frmlista_cartao},
  xloc_cartao in 'fnts\xloc_cartao.pas' {frmxloc_cartao},
  produto_serial_ficha in 'fnts\produto_serial_ficha.pas' {frmProduto_serial_ficha},
  notafiscal_importacupom in 'fnts\notafiscal_importacupom.pas' {frmnotafiscal_importacupom},
  xloc_cst in 'fnts\xloc_cst.pas' {frmxloc_cst},
  xloc_cidade in 'fnts\xloc_cidade.pas' {frmxloc_cidade},
  cidade in 'fnts\cidade.pas' {frmCidade},
  venda_item_2 in 'fnts\venda_item_2.pas' {frmvenda_item_2},
  cor in 'fnts\cor.pas' {frmcor},
  Lista_ABC_Marca_Grupo in 'fnts\Lista_ABC_Marca_Grupo.pas' {frmLista_ABC_Marca_Grupo},
  importa_nfe in 'fnts\importa_nfe.pas' {frmimporta_nfe},
  fluxo_caixa in 'fnts\fluxo_caixa.pas' {frmFluxo_Caixa},
  DRE in 'fnts\DRE.pas' {frmDRE},
  status in 'fnts\status.pas' {frmStatus},
  email in 'fnts\email.pas',
  webcam2 in 'fnts\webcam2.pas' {frmwebcam2},
  CEST in 'fnts\CEST.pas' {frmCEST},
  xloc_csosn in 'fnts\xloc_csosn.pas' {frmxloc_csosn},
  os_item_2_Auto in 'fnts\OS\os_item_2_Auto.pas' {frmos_item_2_Auto},
  xloc_cnae in 'fnts\xloc_cnae.pas' {frmxloc_cnae},
  OpNatureza in 'fnts\OpNatureza.pas' {frmOpNatureza},
  UFuncoes in 'fnts\UFuncoes.pas',
  orcamento_grade in 'fnts\orcamento_grade.pas' {frmorcamento_grade},
  orcamento_serial in 'fnts\orcamento_serial.pas' {frmOrcamento_serial},
  formas_pgto in 'fnts\formas_pgto.pas' {frmFormas},
  os_item_3 in 'fnts\os_item_3.pas' {frmOS_item},
  Vcl.Themes,
  Vcl.Styles,
  tabela_preco in 'fnts\tabela_preco.pas' {frm_tb_preco},
  Ncm in 'fnts\Ncm.pas' {frmNcm},
  LockApplicationInterface in '..\FNTS_Comuns\LockApplicationInterface.pas' {Bloqueio},
  LoginWindow_U in '..\FNTS_Comuns\LoginWindow_U.pas' {frmLoginWindow},
  notafiscal in '..\FNTS_Comuns\notafiscal.pas' {frmnotafiscal},
  notafiscal_item2 in '..\FNTS_Comuns\notafiscal_item2.pas' {frmNotaFiscal_Item2},
  notafiscal_menu in '..\FNTS_Comuns\notafiscal_menu.pas' {frmnotafiscal_menu},
  sintegra_gerar in '..\FNTS_Comuns\sintegra_gerar.pas' {frmsintegra_gerar},
  sobre in '..\FNTS_Comuns\sobre.pas' {Form_sobre},
  splash in '..\FNTS_Comuns\splash.pas' {frmsplash},
  venda_fechamento in '..\FNTS_Comuns\venda_fechamento.pas' {frmvenda_fechamento},
  venda_impressao in '..\FNTS_Comuns\venda_impressao.pas' {frmvenda_impressao},
  senha in '..\FNTS_Comuns\senha.pas' {frmsenha},
  Unit_ativar in '..\FNTS_Comuns\Unit_ativar.pas' {Form_ativar},
  JustificativaInutilizacaoNFe in '..\FNTS_Comuns\JustificativaInutilizacaoNFe.pas' {frmJustificativaInutilizacaoNFe},
  senha_caixa in '..\FNTS_Comuns\senha_caixa.pas' {frmsenha_caixa},
  ExportaXML in '..\FNTS_Comuns\ExportaXML.pas' {FRMExportaXML},
  GridOrcamentos in '..\FNTS_Comuns\GridOrcamentos.pas' {frmGridOrcamentos},
  ManutencaoProduto in 'fnts\ManutencaoProduto.pas' {frmManutencaoProduto},
  AjustaGradeProduto in 'fnts\AjustaGradeProduto.pas' {frmAjustaGradeProduto},
  Texto in '..\FNTS_Comuns\Texto.pas' {frmTexto},
  ConversaoUnidade in 'fnts\ConversaoUnidade.pas' {frmConversaoUnidade},
  loc_paises in 'fnts\loc_paises.pas' {frmloc_paises},
  DivergenciaAtualizacaoNCM in '..\FNTS_Comuns\DivergenciaAtualizacaoNCM.pas' {frmDivergenciaAtualizacaoNCM},
  AtualizaIBPT in '..\FNTS_Comuns\AtualizaIBPT.pas' {frmAtualizaIBPT},
  IcmsUF in 'fnts\IcmsUF.pas' {frmIcmsUF},
  PartilhaICMS in 'fnts\PartilhaICMS.pas' {frmPartilhaICMS},
  ItensOrcamento in 'fnts\ItensOrcamento.pas' {frmItensOrcamento},
  TextoCartaCobranca in 'fnts\TextoCartaCobranca.pas' {frmTextoCartaCobranca},
  carta_cobranca in 'fnts\carta_cobranca.pas' {frmCarta_cobranca},
  Unidades in 'fnts\Unidades.pas' {frmUnidades},
  Extras in 'fnts\Extras.pas' {frmExtras},
  ListaNfeBaixar in 'fnts\ListaNfeBaixar.pas' {frmListaNfeBaixar},
  AlteraItemVenda in 'fnts\AlteraItemVenda.pas' {frmAlteraItemVenda},
  TabelaANP in 'fnts\TabelaANP.pas' {frmTabelaANP},
  RetornaEndereco in 'fnts\RetornaEndereco.pas' {frmRetornaEndereco},
  CadastroEtiquetas in 'fnts\CadastroEtiquetas.pas' {frmCadastroEtiquetas},
  ImpressaoEtiquetas in 'fnts\ImpressaoEtiquetas.pas' {frmImpressaoEtiquetas},
  ConsultaCPF in 'fnts\ConsultaCPF.pas' {frmConsultaCPF},
  ConsultaCNPJ in 'fnts\ConsultaCNPJ.pas' {frmConsultaCNPJ},
  Impressoras in 'fnts\Impressoras.pas' {frmImpressoras},
  os_item_2 in 'fnts\OS\os_item_2.pas' {frmOS_item_2},
  FechamentoCegoConciliar in 'fnts\FechamentoCegoConciliar.pas' {frmFechamentoCegoConciliar},
  Csosn in 'fnts\Csosn.pas' {frmCsosn},
  convenio_pgto in 'fnts\convenio_pgto.pas' {frmconvenio_pgto},
  CadMaquina in 'fnts\CadMaquina.pas' {frmCadMaquina},
  CadastroCliente in 'fnts\CadastroCliente.pas',
  OnLine in '..\FNTS_Comuns\OnLine.pas' {frmOnLine},
  contasreceber_recibo in 'fnts\contasreceber_recibo.pas' {frmcontasreceber_recibo},
  TabelaPrecoGrupo in 'TabelaPrecoGrupo.pas' {frmTabelaPrecoGrupo},
  BaixaAutomatica in 'fnts\BaixaAutomatica.pas' {frmBaixaAutomatica},
  Boleto in 'fnts\Boleto.pas' {frmBoleto},
  obsVenda in 'fnts\obsVenda.pas' {frmobsVenda},
  uFrmMaster in '..\FNTS_Comuns\uFrmMaster.pas' {FrmMaster},
  MenuTransferencia in 'fnts\MenuTransferencia.pas' {frmMenuTransferencia},
  EnviaTransferencia in 'fnts\EnviaTransferencia.pas' {frmEnviaTransferencia},
  BaixaTransferencia in 'fnts\BaixaTransferencia.pas' {frmBaixaTransferencia},
  ConsultaEstoqueFilial in '..\FNTS_Comuns\ConsultaEstoqueFilial.pas' {frmConsultaEstoqueFilial},
  empresa in 'fnts\empresa.pas' {frmempresa},
  Empresas in 'fnts\Empresas.pas' {frmEmpresas},
  Loc_ConversorUnidade in 'fnts\Loc_ConversorUnidade.pas' {frmLoc_ConversorUnidade},
  ConversorUnImpXml in 'fnts\ConversorUnImpXml.pas' {frmConversorUnImpXml},
  UCBase in '..\FNTS_Comuns\UCBase.pas',
  ConfigTabelas in 'fnts\ConfigTabelas.pas' {frmConfigTabelas},
  SelecionaEmpresa in 'fnts\SelecionaEmpresa.pas' {frmSelecionaEmpresa},
  xloc_produto in 'fnts\xloc_produto.pas' {frmxloc_produto},
  loc_filial in 'fnts\loc_filial.pas' {frmloc_filial},
  produto_falta in 'fnts\produto_falta.pas' {frmproduto_falta},
  ResultadoWebService in '..\FNTS_Comuns\ResultadoWebService.pas' {frmResultadoWebService},
  SelecionaNFeDevolucao in 'fnts\SelecionaNFeDevolucao.pas' {frmSelecionaNFeDevolucao},
  LiberaPDV in 'fnts\LiberaPDV.pas' {frmLiberaPDV},
  Exportar_Sweada_Csd in 'Exportar_Sweada_Csd.pas' {frmExportar_Sweada_Csd},
  uGestLotes in 'fnts\uGestLotes.pas' {frmLotes},
  uLancLotes in 'fnts\uLancLotes.pas' {frmLancLotes},
  uLote in 'fnts\uLote.pas',
  uLoteItens in 'fnts\uLoteItens.pas',
  uRelLotes in 'fnts\uRelLotes.pas' {frmRelLotes};

{$R *.res}

begin
  Application.Initialize;
  frmsplash := Tfrmsplash.Create(Application);
  frmsplash.show;
  frmsplash.Update;
  Application.Title := 'SOS - 5.1';
  Application.CreateForm(Tfrmmodulo, frmmodulo);
  Application.CreateForm(TfrmPrincipal, frmPrincipal);
  Application.CreateForm(TFrmMaster, FrmMaster);
  frmsplash.Close;
  FreeAndNil(frmsplash);
  application.ProcessMessages;
  Application.Run;
end.

